version: 2

sphinx:
  configuration: conf.py

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
    
# Install our python package before building the docs
python:
  version: 3.8
  install:
    - requirements: requirements.txt

sphinx:
  fail_on_warning: true
  
formats:
  - pdf
  - epub
