version: 2

sphinx:
  configuration: docs/conf.py
    
# Install our python package before building the docs
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt

sphinx:
  fail_on_warning: false
  
formats:
  - pdf
  - epub
